version: '3.8'

services:
  metrics-test:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app
    ports:
      - "5050:5050" # Application port
      - "9090:9090" # JMX port
    env_file: 
      - .env
    environment:
      ATATUS_APP_NAME: java-metrics-an-test
      JAVA_TOOL_OPTIONS: >
          -Dcom.sun.management.jmxremote=true
          -Dcom.sun.management.jmxremote.port=9090
          -Dcom.sun.management.jmxremote.rmi.port=9090
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.ssl=false
          -Dcom.sun.management.jmxremote.local.only=false
          -Djava.rmi.server.hostname=localhost

          -Delastic.apm.service_name=metrics-test 
          -Delastic.apm.api_key=RUd0N2dwZ0JyOXlwaXRQSmtzYzY6MVlkU2tZVGFpVG5Ca21OOURjc2NHdw== 
          -Delastic.apm.server_url=https://my-observability-project-eb807a.apm.asia-south1.gcp.elastic.cloud:443 
          -Delastic.apm.environment=production 
          -Delastic.apm.application_packages=com.mt 
    networks:
      - metrics-network

networks:
  metrics-network:
    driver: bridge
