services:
  # metrics-test:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app
  #   ports:
  #     - "5050:5050" # Application port
  #     - "5051:5051" # Management port
  #     - "9090:9090" # JMX port
  #   env_file: 
  #     - .env
  #   # environment:
  #     # JAVA_TOOL_OPTIONS: >
          
  #     #     -Dcom.sun.management.jmxremote=true
  #     #     -Dcom.sun.management.jmxremote.port=9090
  #     #     -Dcom.sun.management.jmxremote.rmi.port=9090
  #     #     -Dcom.sun.management.jmxremote.authenticate=false
  #     #     -Dcom.sun.management.jmxremote.ssl=false
  #     #     -Dcom.sun.management.jmxremote.local.only=false
  #     #     -Djava.rmi.server.hostname=localhost

  #     #     -Delastic.apm.service_name=metrics-test 
  #     #     -Delastic.apm.api_key=RUd0N2dwZ0JyOXlwaXRQSmtzYzY6MVlkU2tZVGFpVG5Ca21OOURjc2NHdw== 
  #     #     -Delastic.apm.server_url=https://my-observability-project-eb807a.apm.asia-south1.gcp.elastic.cloud:443 
  #     #     -Delastic.apm.environment=production 
  #     #     -Delastic.apm.application_packages=com.mt 
  #   networks:
  #     - metrics-network

  metrics-test-1:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app-1
    ports:
      - "5051:5050"
    env_file: 
      - .env
    networks:
      - metrics-network

  metrics-test-2:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app-2
    ports:
      - "5052:5050"
    env_file: 
      - .env
    networks:
      - metrics-network

  metrics-test-3:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app-3
    ports:
      - "5053:5050"
    env_file: 
      - .env
    networks:
      - metrics-network

  metrics-test-4:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app-4
    ports:
      - "5054:5050"
    env_file: 
      - .env
    networks:
      - metrics-network

  metrics-test-5:
    build:
      context: ./metrics-test
      dockerfile: Dockerfile
    container_name: metrics-test-app-5
    ports:
      - "5055:5050"
    env_file: 
      - .env
    networks:
      - metrics-network

  # metrics-test-6:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-6
  #   ports:
  #     - "5056:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-7:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-7
  #   ports:
  #     - "5057:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-8:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-8
  #   ports:
  #     - "5058:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-9:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-9
  #   ports:
  #     - "5059:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-10:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-10
  #   ports:
  #     - "5060:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-11:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-11
  #   ports:
  #     - "5061:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-12:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-12
  #   ports:
  #     - "5062:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-13:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-13
  #   ports:
  #     - "5063:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-14:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-14
  #   ports:
  #     - "5064:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-15:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-15
  #   ports:
  #     - "5065:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-16:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-16
  #   ports:
  #     - "5066:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-17:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-17
  #   ports:
  #     - "5067:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-18:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-18
  #   ports:
  #     - "5068:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-19:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-19
  #   ports:
  #     - "5069:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-20:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-20
  #   ports:
  #     - "5070:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-21:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-21
  #   ports:
  #     - "5071:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-22:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-22
  #   ports:
  #     - "5072:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-23:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-23
  #   ports:
  #     - "5073:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-24:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-24
  #   ports:
  #     - "5074:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-25:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-25
  #   ports:
  #     - "5075:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-26:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-26
  #   ports:
  #     - "5076:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-27:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-27
  #   ports:
  #     - "5077:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-28:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-28
  #   ports:
  #     - "5078:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-29:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-29
  #   ports:
  #     - "5079:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-30:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-30
  #   ports:
  #     - "5080:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-31:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-31
  #   ports:
  #     - "5081:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-32:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-32
  #   ports:
  #     - "5082:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-33:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-33
  #   ports:
  #     - "5083:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-34:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-34
  #   ports:
  #     - "5084:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-35:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-35
  #   ports:
  #     - "5085:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-36:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-36
  #   ports:
  #     - "5086:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-37:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-37
  #   ports:
  #     - "5087:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-38:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-38
  #   ports:
  #     - "5088:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-39:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-39
  #   ports:
  #     - "5089:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-40:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-40
  #   ports:
  #     - "5090:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-41:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-41
  #   ports:
  #     - "5091:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-42:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-42
  #   ports:
  #     - "5092:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-43:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-43
  #   ports:
  #     - "5093:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-44:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-44
  #   ports:
  #     - "5094:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-45:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-45
  #   ports:
  #     - "5095:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-46:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-46
  #   ports:
  #     - "5096:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-47:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-47
  #   ports:
  #     - "5097:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-48:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-48
  #   ports:
  #     - "5098:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-49:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-49
  #   ports:
  #     - "5099:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

  # metrics-test-50:
  #   build:
  #     context: ./metrics-test
  #     dockerfile: Dockerfile
  #   container_name: metrics-test-app-50
  #   ports:
  #     - "5100:5050"
  #   env_file: 
  #     - .env
  #   networks:
  #     - metrics-network

networks:
  metrics-network:
    driver: bridge